<?php 

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

function getGitlabToken() {
    // https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html
    $gitlab_token = defined('WORDSBY_GITLAB_API_TOKEN') ? WORDSBY_GITLAB_API_TOKEN : false;
    
    if (!$gitlab_token) return;
    return $gitlab_token;
}

function getGitlabClient () {
    return \Gitlab\Client::create('https://gitlab.com/api/v4/')
        ->authenticate(getGitlabToken(), \Gitlab\Client::AUTH_URL_TOKEN);

    // $project = $client->api('projects')->create('My Project', array(
    // 'description' => 'This is a project',
    // 'issues_enabled' => false
    // ));
}

function showProject() {
    $client = getGitlabClient();
    $project = $client->api('projects')->show(9933940);
    return $project;
    // write_log($project);
}

function getMasterCommit() {
    $client = getGitlabClient();
    $commits = $client->api('repositories')->commits(9933940);
    write_log($commits); 
}

function createNewContentBranch() {
    $client = getGitlabClient();
    
    $client->api('repositories')->createBranch(9933940, 'new-content-branch', ['ref' => 'master']);
}

function commitNewContent() {
    $client = getGitlabClient();
    write_log($client->api('repositories')->createCommit(9933940, array(
        'branch' => 'new-content-branch2', 
        'start_branch'=> 'master',
        'commit_message' => 'Content update from site.com',
        'actions' => array(
            array(
                'action' => 'create',
                'file_path' => 'test',
                'content' => 'commiting from php!',
                'encoding' => 'text'
            )
        ),
        'author_email' => 'tyler@test.com',
        'author_name' => 'test!'
    ))); 

}

// prevent init from being called twice!
remove_filter('wp_head','adjacent_posts_rel_link_wp_head',10);

add_action('init', 'commitNewContent');
// add_action('init', 'createNewContentBranch');
// add_action('save_post', 'connectToGitlab');

?>